opowiesc/config/routes.rb
Opowiesc::Application.routes.draw do 
 
  resources :galleries

 resources :tales do
  resources :comments
end 
  get "user/index"

  get "user/create"

  get "user/new"

  get "user/destroy"

  get "user/show"

  devise_for :users

  get "account/login"

  get "account/logout"
get 'tags/:tag', to: 'tales#index', as: :tag
 resources :tales 
root :to => 'tales#index'

end

opowiesc/app/models/tale.rb
class Tale < ActiveRecord::Base
  belongs_to :user
  attr_accessible :link, :title, :rate, :rating, :tag_list
  acts_as_taggable
  has_many :comments, :as => :commentable
end

opowiesc/app/controllers/tales_controller.rb
class TalesController < ApplicationController
  # GET /tales
  # GET /tales.json
  
  def index
       param1 = params[:id] 
    if params[:tag]
    @tales = Tale.tagged_with(params[:tag])
  else
    @tales = Tale.all
  end
  
    unless @current_user.nil?
    session[:user_id] = @current_user.id
   
  end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tales }
    end
  end
  
  # GET /tales/1
  # GET /tales/1.json
  def show
    @tale = Tale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tale }
    end
  end

  # GET /tales/new
  # GET /tales/new.json
  def new
    @tale = Tale.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tale }
    end
  end

  # GET /tales/1/edit
  def edit
    @tale = Tale.find(params[:id])
  end

  # POST /tales
  # POST /tales.json
  def create
    @tale = Tale.new(params[:tale])

    respond_to do |format|
      if @tale.save
        format.html { redirect_to @tale, notice: 'Tale was successfully created.' }
        format.json { render json: @tale, status: :created, location: @tale }
      else
        format.html { render action: "new" }
        format.json { render json: @tale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tales/1
  # PUT /tales/1.json
  def update
    @tale = Tale.find(params[:id])

    respond_to do |format|
      if @tale.update_attributes(params[:tale])
        format.html { redirect_to @tale, notice: 'Tale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tales/1
  # DELETE /tales/1.json
  def destroy
    @tale = Tale.find(params[:id])
    @tale.destroy

    respond_to do |format|
      format.html { redirect_to tales_url }
      format.json { head :no_content }
    end
  end
end

opowiesc/app/helpers/tales_helper.rb
module TalesHelper
   
end

opowiesc/app/views/tales/_form.html.erb
<%= simple_form_for(@tale) do |f| %>
  <% if @tale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tale.errors.count, "error") %> prohibited this tale from being saved:</h2>

      <ul>
      <% @tale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link, :input_html => { :class => "span6" } %>
   </div>

  <div class="field">
  <%= f.input :rate, :collection => 1..5  %>
     </div>
  <div class="field">
   <%= f.label :tag_list, "Tags (separated by commas)" %><br />
   <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

opowiesc/app/views/tales/edit.html.erb
<%- model_class = Tale -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

opowiesc/app/views/tales/index.html.erb
<%- model_class = Tale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<div id="tag_cloud">
  <% tag_cloud Tale.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%= model_class.human_attribute_name(:ratings) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tales.each do |tale| %>
      <tr>
          
        <td><%= link_to tale.id, tale_path(tale) %>  
            <br> Tags: <%= raw tale.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></br>      
        </td>
        <td><%= tale.title %></td>
        <td><%= link_to tale.link, tale.link %></td>
        <td><%= tale.rate %></td>
        <td><%=l tale.created_at %></td>
        <td>
   
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tale_path(tale), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tale_path(tale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
      
           <br> <%= link_to "Comment", 'tales/1/comments' %> </br>

       
         </td>  
      </tr>
       
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tale_path,
            :class => 'btn btn-primary' %>
<p>
<%= Time.now %>
</p>

opowiesc/app/views/tales/new.html.erb
<%- model_class = Tale -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

opowiesc/app/views/tales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @tale.title %>
</p>

<p>
  <b>Link:</b>
  <%= @tale.link %>
</p>
 <b>Your rating:</b>
  <%= @tale.rate %>
</p>


<p class="submitted_by">
Submitted by:
<%= @tale.user %>
</p>

<%= link_to 'Edit', edit_tale_path(@tale) %> |
<%= link_to 'Back', tales_path %>