opowiesc/config/routes.rb
Opowiesc::Application.routes.draw do 
 
  resources :galleries

 resources :tales do
  resources :comments
end 
  get "user/index"

  get "user/create"

  get "user/new"

  get "user/destroy"

  get "user/show"

  devise_for :users

  get "account/login"

  get "account/logout"
get 'tags/:tag', to: 'tales#index', as: :tag
 resources :tales 
root :to => 'tales#index'

end

opowiesc/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commantable, :polymorphic => true
  attr_accessible :content, :tale_id
end

opowiesc/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def index
  @commentable = find_commentable
  @comments = @commentable.comments
end

def create
  @commentable = find_commentable
  @comment = @commentable.comments.build(params[:comment])
  if @comment.save
    flash[:notice] = "Successfully created comment."
    redirect_to :id => nil
  else
    render :action => 'new'
  end
end

private

def find_commentable
  params.each do |name, value|
    if name =~ /(.+)_id$/
      return $1.classify.constantize.find(value)
    end
  end
  nil
end
end

opowiesc/app/helpers/comments_helper.rb
module CommentsHelper
end

opowiesc/app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :tale_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

opowiesc/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

opowiesc/app/views/comments/index.html.erb
<h1>Comments</h1>

<ul id="comments">
  <% @comments.each do |comment| %>
    <%= comment.content %></br>
  <% end %>
</ul>

<h2>New Comment</h2>
<%= form_for [@commentable, Comment.new] do |f| %>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 5 %>
  </div>
  <div class="actions">
    <%= submit_tag "Add comment" %>
  </div>
<% end %>
 
  

opowiesc/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

opowiesc/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>Tale:</b>
  <%= @comment.tale_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>