opowiesc/config/routes.rb
Opowiesc::Application.routes.draw do 
 
  resources :galleries

 resources :tales do
  resources :comments
end 
  get "user/index"

  get "user/create"

  get "user/new"

  get "user/destroy"

  get "user/show"

  devise_for :users

  get "account/login"

  get "account/logout"
get 'tags/:tag', to: 'tales#index', as: :tag
 resources :tales 
root :to => 'tales#index'

end

opowiesc/app/models/gallery.rb
class Gallery < ActiveRecord::Base
   attr_accessible :photo
   has_attached_file :photo
end

opowiesc/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end
end

opowiesc/app/helpers/galleries_helper.rb
module GalleriesHelper
end

opowiesc/app/views/galleries/_form.html.erb
<%= simple_form_for(@gallery, :html => { :multipart => true }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>
  <%= f.file_field :photo %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

opowiesc/app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

opowiesc/app/views/galleries/index.html.erb
<h1>Listing galleries</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @galleries.each do |gallery| %>
  <tr>
     <%= image_tag  gallery.photo.url %>
<br />
    <td><%= link_to 'Show', gallery %></td>
    <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
    <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery', new_gallery_path %>

opowiesc/app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

opowiesc/app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>
 <b>Photo:</b>
<% if @gallery.photo? %>
  <%= image_tag @gallery.photo.url %>
  <br />
  <%= link_to @gallery.photo.url, @gallery.photo.url %>
<% end %>
<br />

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>